### ISSUE TITLE
Add credit retirement data to the state

### ISSUE THREAD

**Issue by ba1ciu** [EmpowerPlastic/empowerchain#523]
We have to modify credit retirement logic to use new `certificates` module. When retiring credits, `certificates`' keeper should be called and new certificate should be created. Certificate object should look as follows:
```yml
type: 0 (CREDIT_RETIREMENT)
owner: address of the wallet retiring the credits # IMPORTANT! If the credits are retired during transfer, we should put the receiver address here
issuer: plastic credit issuer's admin address
data:
  denom: credit denom
  amount: retired amount
  retiring_entity_address: same as the owner above
  retiring_entity_name: input from the user during retirement
  retiring_entity_additional_data: input from the user during retirement
```

`MsgRetireCredits` should be updated to include additional retirerer name and data:
```proto
message MsgRetireCredits {
  option (cosmos.msg.v1.signer) = "owner";

  string owner = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string denom = 2;
  uint64 amount = 3;
  string retiring_entity_name = 4;
  string retiring_entity_additional_data = 5;
```
}

`MsgTransferCredits` should also be updated as follows:
```proto
message MsgTransferCredits {
  option (cosmos.msg.v1.signer) = "from";

  string from = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string to = 2 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string denom = 3;
  uint64 amount = 4;
  bool retire = 5;
  string retiring_entity_name = 6;
  string retiring_entity_additional_data = 7;
} 
```

CLI should be updated with additional data and name params for `retire` and `transfer` commands.
